### ISSUE TITLE
Pizza for Refresh OKC (5-31)

### ISSUE THREAD

**Issue by RicksConcepts** [techlahoma/techlahoma#101]
Respectfully requesting pizza for approx 30 people for the refreshOKC meeting on 2016-05-31@ the404 @amandaharlin

**Comment by RicksConcepts** [comment]
@amandaharlin

**Comment by the-simian** [comment]
I think this all happened. closing

**Comment by RicksConcepts** [comment]
Yep, we're good to go! Thanks! I'll mark it on my calendar to close these the day after.

**Comment by the-simian** [comment]
no worries, if you don't get to closing we can, was just browsing some of the issues. I'm planning (after I finish a lot of accounting stuff) to sweep through a lot of them
