### ISSUE TITLE
Slackbot for techlahoma slack

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/techlahoma#102]
If anyone has time and motivation to write a slackbot, it'd really help us welcome new members. The slack could automatically say hello to new techlahomans joining the slack and dm the person a link to our code of conduct. Ideas are def welcome! :-)

**Comment by datachomp** [comment]
I wonder how much of that can be done by adding some rules to the default slackbot provided with each channel - vs having to write/maintain an external slackbot

**Comment by amandaharlin** [comment]
Great idea, Rob!

**Comment by datachomp** [comment]
Whelp... I'm not seeing anything in the default slackbot controls for on-boarding events or anything other than word match responses.    Sigh, was hoping for an easy win here.

Here is a basic bot someone wrote in python that would accomplish this task and is easily deployable to heroku - https://medium.com/@izzydoesizzy/create-a-slack-bot-that-privately-greets-new-users-in-5-easy-steps-a38eabeabcb5#.bn2unvhcg

**Comment by matthewreily** [comment]
I like @datachomp idea for an easy welcome bot.  If we want a custom bot I can volunteer to get that up and going.  I help maintain a (hubot) slackbot for my company atm.  Maybe we start off with a simple welcome bot then upgrade to a new custom one v2. thoughts @amandaharlin

**Comment by amandaharlin** [comment]
Whoa, very cool! That'd be awesome @matthewreily. If you wanted to start a
project like that with a hello, a link to techlahoma.org, and a link to the
coc - that'd probably be all we need to start. 😄

**Comment by matthewreily** [comment]
Added a new slack bot to our heroku account under the heroku@techlahoma.org account. It is the welcome bot that @datachomp mentioned in a previous comment.  The welcome message can easily be modified by logging into our account and editing a variable under the greeting bot's settings.

Followed this tutorial to set us up https://medium.com/@izzydoesizzy/create-a-slack-bot-that-privately-greets-new-users-in-5-easy-steps-a38eabeabcb5#.bn2unvhcg

**Comment by matthewreily** [comment]
Closing this since we implemented this 2 months ago.
