### ISSUE TITLE
OKC# June meeting food

### ISSUE THREAD

**Issue by matthewreily** [techlahoma/techlahoma#103]
Need food ordered for approx. 25 people for the June 6th meeting @11:30

**Comment by amandaharlin** [comment]
thanks @matthewreily :) i'll bring sodas and plates too 👍  <img width="606" alt="screen shot 2016-06-05 at 9 38 22 pm" src="https://cloud.githubusercontent.com/assets/716644/15810593/e8e85736-2b65-11e6-9545-41a00963281c.png">
