### ISSUE TITLE
okcruby food for June 9th Meeting

### ISSUE THREAD

**Issue by datachomp** [techlahoma/techlahoma#106]
group: okcruby
food type: ?
guest approximation: 15
meeting date: June 9th, 2016 11:30

For visibility,
organizers: @jagthedrummer @piisalie @datachomp

**Comment by jagthedrummer** [comment]
Thanks, @datachomp!

**Comment by amandaharlin** [comment]
Food is ordered.

**Comment by jagthedrummer** [comment]
Thanks, @amandaharlin! 😄
