### ISSUE TITLE
Pizza for RefreshOKC (June 28th)

### ISSUE THREAD

**Issue by RicksConcepts** [techlahoma/techlahoma#108]
Respectfully requesting pizza for approx 25ish people for the refreshOKC meeting on 28Jun16 @ the 404 around 630pm. 

I had this thought since I've been educating myself on Js that I'd write some cool scripting but then I was sidetracked by beer and burgers. Next month though!

**Comment by datachomp** [comment]
cool scripting of what?

**Comment by RicksConcepts** [comment]
More like a clever way of asking for pizza essentially.

**Comment by datachomp** [comment]
Ahhh cool!  This is exactly how the ruby group orders their food and it is made really easy through the github api which is accommodating for many languages:   https://developer.github.com/libraries/

In ruby, it was incredibly simple to make our own little template :
```
require 'octokit'
repo = 'techlahoma/techlahoma'

client = Octokit::Client.new(:access_token => ENV['github_api_token'])

group = 'okcruby'
meeting_date = DateTime.new(meeting_date)
organizers = "hedrummer isalie"

title = "#{group} food for #{meeting_date.strftime("%B %d")} Meeting"
body = "group: #{group}
food type: ?
guest approximation: 15
meeting date: #{meeting_date.strftime("%A, %b %d %Y at %l:%M %p ")}

For visibility,
organizers: #{organizers}"

client.create_issue(repo, title, body, {labels: ['pizza']})
```

It looks like refreshokc is using meetup.com which isn't very good at letting you know, programmatically ,  when an event is actually going to happen...but not impossible.  The best I have found is, using your language of choice, download the ical  file they offer, and just start parsing its data to isolate calendar date in it.

**Comment by amandaharlin** [comment]
🍕🍕🍕
