### ISSUE TITLE
Food/drinks for Code for OKC June 27th meeting

### ISSUE THREAD

**Issue by mkchandler** [techlahoma/techlahoma#109]
Pizza/drinks order for tonight's Code for OKC meeting:

Attendees: 10-12 (based on Meetup RSVP + previous history of people who show up)
Number of pizzas: 3 large (2 pepperoni, 1 cheese)
Soda: 2 (1 coke, 1 sprite)
Delivery time: Monday, June 27th at 6:00 PM
Location: Prototek

cc: @amandaharlin

**Comment by amandaharlin** [comment]
food has been ordered. thanks @mkchandler!
