### ISSUE TITLE
okcruby food for July 14 Meeting

### ISSUE THREAD

**Issue by datachomp** [techlahoma/techlahoma#112]
group: okcruby
food type: ?
guest approximation: 15
meeting date: Thursday, Jul 14 2016 at 11:30 AM 

For visibility,
organizers: @jagthedrummer @piisalie @datachomp

**Comment by amandaharlin** [comment]
ordered y'all a party platter from jimmy johns. they don't deliver 2 liters (the one nice benefit of pizza) so someone will need to pick up drinks. there might still be some soda at prototek from c#/py, but that's not certain.

**Comment by jagthedrummer** [comment]
Oh, thanks @amandaharlin! Did you happen to get some veggie only options in there? If not we can improvise something.

**Comment by amandaharlin** [comment]
i did, got a veggie sandwich in there :)
