### ISSUE TITLE
Pizza for RefreshOKC (August 30th)

### ISSUE THREAD

**Issue by RicksConcepts** [techlahoma/techlahoma#120]
Respectfully requesting pizza for approx 25ish people for the refreshOKC meeting on 30Aug16 @ the OBI (901 N Lincoln Blvd, Oklahoma City, OK 73104) in the Addison Group conference room around 630pm.

**Comment by RicksConcepts** [comment]
@amandaharlin

**Comment by amandaharlin** [comment]
<img width="489" alt="screen shot 2016-08-29 at 11 39 44 pm" src="https://cloud.githubusercontent.com/assets/716644/18076251/e57518e0-6e41-11e6-81c8-9a64a4149d06.png">

**Comment by amandaharlin** [comment]
please let our veggie peeps know they've got 2 pizza options (and whatever we manage to bring along! lol)
