### ISSUE TITLE
Food and Prototek access for OKC# Meetup on 9-12

### ISSUE THREAD

**Issue by matthewreily** [techlahoma/techlahoma#123]
OKC# has 38 members currently signed up for tomorrow's meeting.  Could we get food ordered and someone to let us in?

**Comment by amandaharlin** [comment]
woot! food ordered. i'll pick up drinks and extra snacks tomorrow and let you in <img width="633" alt="screen shot 2016-09-11 at 10 52 55 pm" src="https://cloud.githubusercontent.com/assets/716644/18424174/89d02f80-7872-11e6-8fab-fcf654a98006.png">

**Comment by seejessicacode** [comment]
42 people at OKC# today.
