### ISSUE TITLE
Food and Drink for September 13 OKC JUG

### ISSUE THREAD

**Issue by jasondlee** [techlahoma/techlahoma#125]
Meeting Date: September 13

Pizza:
-     2 cheese
-     2 pepperoni
-     2 sausage
-     2 supreme
-     2 veggie

Drinks:
-     2 Coke
-     1 Sprite
-     1 Dr. Pepper
-     1 Diet Coke (just for @drodmaster : )
-     20 plates

**Comment by amandaharlin** [comment]
Ordered as requested. Should arrive at 11:15 - 11:30.Plates cups, and napkins are already at prototek.
