### ISSUE TITLE
Pizza/drinks for Code for OKC on Monday, Sep 26th

### ISSUE THREAD

**Issue by mkchandler** [techlahoma/techlahoma#128]
Pizza/drinks order for September Code for OKC meeting:

Attendees: 10
Number of pizzas: 3 large (2 pepperoni, 1 cheese)
Drinks: 1 Coke
Delivery time: Monday, September 26th at 6:00 PM
Location: Prototek

cc: @amandaharlin

**Comment by amandaharlin** [comment]
pizza has been ordered. thanks so much! 👍 ^o^ <img width="632" alt="screen shot 2016-09-26 at 1 02 33 pm" src="https://cloud.githubusercontent.com/assets/716644/18845967/81bfc9c2-83e9-11e6-8c00-c266ff78b1ad.png">

**Comment by mkchandler** [comment]
Thanks @amandaharlin!
