### ISSUE TITLE
Pizza/Drinks for October OKGD Meeting

### ISSUE THREAD

**Issue by goldfire** [techlahoma/techlahoma#130]
Pizza/drinks order for Thursday, October 6 Oklahoma Game Developers meeting:

**Attendees:** ~20
**Number of pizzas:** 5 large (3 pepperoni, 1 sausage, 1 cheese)
**Soda:** 3 (1 sprite, 1 coke, 1 coke zero)
**Delivery time:** Thursday, October 6th at 7:00 PM
**Location:** Prototek

**Comment by the-simian** [comment]
thanks for opening this early :)
