### ISSUE TITLE
Pizza for Oklahoma PHP, October 6th

### ISSUE THREAD

**Issue by michalcarson** [techlahoma/techlahoma#131]
Only 5 RSVPs so far on Meetup. Two pizzas would be lovely.

Meeting is at OBI in the Addison conference room (3rd floor) at 6:30 p.m. Thursday, October 6th.

Contacts: Mike Collins (Addison, 405.496.8101) and Jacques Ball (presenter, 405.816.2951). Sorry, I won't be there for this meeting.

First time we have tried to arrange pizza this way, so let me know how to make this work. Thanks.

**Comment by amandaharlin** [comment]
Thanks Michael! I'll post again once it's ordered. (And thank you
@seejessicacode 😃)

**Comment by amandaharlin** [comment]
![screenshot_20161006-173612](https://cloud.githubusercontent.com/assets/716644/19173150/781c4f9e-8beb-11e6-989d-3f7b59f54e91.jpg) pizza and deinks will be on the way at 6:30 to the 3rd floor :-)
