### ISSUE TITLE
Food and Drink for October 11 OKC JUG

### ISSUE THREAD

**Issue by jasondlee** [techlahoma/techlahoma#138]
Meeting Date: October 11

Pizza:
- 2 cheese
- 2 pepperoni
- 2 sausage
- 2 supreme
- 2 veggie

Drinks:
- 2 Coke
- 1 Sprite
- 1 Dr. Pepper
- 1 Diet Coke 

20 plates

**Comment by amandaharlin** [comment]
<img width="569" alt="screen shot 2016-10-11 at 9 16 37 am" src="https://cloud.githubusercontent.com/assets/716644/19273822/952e72c8-8f93-11e6-9155-ddc2e5d85499.png">

**Comment by seejessicacode** [comment]
![okc_jug_receipt-20161011](https://cloud.githubusercontent.com/assets/943398/19281492/2b6bcbca-8fb0-11e6-9ebc-93c315face17.jpg)
