### ISSUE TITLE
Food Drinks and Prototek Accesss October 10th For OKC#

### ISSUE THREAD

**Issue by matthewreily** [techlahoma/techlahoma#139]
Could we please get food and drinks ordered for the OKC# meeting on Monday October 11th?  We will also need someone to let us into Prototek at 11:15 a.m. please.

**Comment by amandaharlin** [comment]
![screenshot_20161010-084933](https://cloud.githubusercontent.com/assets/716644/19238371/dd41db0e-8ec6-11e6-93ee-b6d383c290d2.jpg)
