### ISSUE TITLE
Arrange food, drink, and venue access for Refresh OKC event | 2016-10-26

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/techlahoma#144]
What: Lightning Talks
When: 2016-10-26 11:30
Where: 901 N. Lincoln Blvd., Oklahoma City

Check meetup for RSVP count: http://www.meetup.com/Refresh-OKC/events/234838934/

**Comment by amandaharlin** [comment]
Pizza and drinks ordered. Also got a salad. Please be sure to let folks know it's up for grabs
