### ISSUE TITLE
Arrange food, drink, and venue access for OK PHP event | 2017-10-16

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/techlahoma#145]
What: Tulsa Meetup
When: 2017-10-16 18:00
Where: 618 East 3rd Street, Tulsa

Check meetup for RSVP count: http://www.meetup.com/OklahomaPHP/events/ddnrmjywnbvb/

**Comment by groovecoder** [comment]
Can someone make me a co-organizer of OK PHP? This meetup is an old recurring meetup listed at our old venue. I need to update it to our new 36°N venue, and change description that it's a combined meetup with TWD (until we recruit a new Tulsa leader for OK PHP who can organize distinct PHP topics & talks).

**Comment by seejessicacode** [comment]
Done!

**Comment by groovecoder** [comment]
Cool, I updated it to reflect that OK PHP Tulsa meetups are currently joined with Tulsa Web Devs, but that we always accept PHP talk submissions for TWD, and we're seeking a dedicated Tulsa meetup organizer for OK PHP.
