### ISSUE TITLE
Pizza/drinks for Code for OKC on 10/24

### ISSUE THREAD

**Issue by mkchandler** [techlahoma/techlahoma#159]
Pizza/drinks order for October Code for OKC meeting:

Attendees: 10
Number of pizzas: 3 large (2 pepperoni, 1 cheese)
Drinks: 1 Coke
Delivery time: Monday, October 24th at 6:00 PM
Location: Prototek

cc: @amandaharlin @seejessicacode

**Comment by seejessicacode** [comment]
Thanks for checking in and posting @mkchandler! I wonder why Techlahoma's Zapier tool didn't catch Code for OKC's new event and automatically handle this. I'll look into it.

**Comment by amandaharlin** [comment]
<img width="560" alt="screen shot 2016-10-24 at 2 59 47 pm" src="https://cloud.githubusercontent.com/assets/716644/19661746/8a0e144a-99fa-11e6-96e6-9b6f39abf411.png">

**Comment by amandaharlin** [comment]
hey matt, jeremy is going to bring over some chairs from ss46 to prototek. just a heads up that you might need to rely on the roll-y office chairs for your main seating.

**Comment by mkchandler** [comment]
@amandaharlin Sounds good! Thanks!

**Comment by mkchandler** [comment]
## Post-meeting summary

- Was there enough food? Yes
- What was the head count? 8
- Did it arrive on time?  No, was 15 minutes late (obviously not a big deal for our group though since we are not doing presentations)
- Was it decent or dissatisfactory in taste, time, etc? Was satisfactory.
