### ISSUE TITLE
Pizza for RefreshOKC (October 26th)

### ISSUE THREAD

**Issue by RicksConcepts** [techlahoma/techlahoma#162]
Respectfully requesting pizza for approx 20ish people for the refreshOKC meeting on 26Wed16 @ the OBI (901 N Lincoln Blvd, Oklahoma City, OK 73104) in the Addison Group conference room at 1130am.

**Comment by seejessicacode** [comment]
#144 Closing duplicate issue.

**Comment by RicksConcepts** [comment]
Thanks Jessica. This is the first I've heard of this so I followed what I thought was the procedure. I'll go ahead and adjust my task list to reflecting verifying the automation instead of making double posts. 

Appreciate it!

**Comment by RicksConcepts** [comment]
- Was there enough food?  - Yep, We had one extra whole pizza but that's ok. It was taken care of and probably would have been gone if it arrived on time. That's not our fault though.
- What was the head count? - About 20
- Did it arrive on time?  - That's a big negatory
- Was it decent or dissatisfactory in taste, time, etc? It was good. They've stepped up their quality of food.
