### ISSUE TITLE
Setup G Suite account for tulsarb.org and railsbridgetulsa.org

### ISSUE THREAD

**Issue by wassimk** [techlahoma/techlahoma#163]
Please, setup tulsarb.org as the primary domain. 
Add railsbridgetulsa.org to it as a secondary domain.

Accounts:
wassim@tulsarb.org with info aliased to it.

I can do the DNS changes when ready, just Slack @wassimk.

**Comment by seejessicacode** [comment]
I didn't know Techlahoma was providing this benefit to their user groups. This will need to be included in the on-boarding package @the-simian and I are building.

@rhoegg when can we get together to review this process?

**Comment by the-simian** [comment]
We'll hit this after the meetup stuff

**Comment by seejessicacode** [comment]
@wassimk since we've transferred tulsarb.org to Techlahoma's DNSimple account, would you consider this resolved? I'm not sure where G Suites fits in this domain request.
