### ISSUE TITLE
Arrange food, drink, and venue access for Code for OKC event | 2016-11-28

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/techlahoma#164]
What: November Hack Night
When: 2016-11-28 18:00
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: http://www.meetup.com/Code-for-OKC/events/235104091/

**Comment by mkchandler** [comment]
@seejessicacode @amandaharlin Looks like the current RSVP count is 15, which is probably a safe number to lock in.

**Comment by amandaharlin** [comment]
i ordered this for 5:45 - simce they've been 15 min late this should arrive at 6pm <img width="560" alt="screen shot 2016-11-28 at 4 11 27 pm" src="https://cloud.githubusercontent.com/assets/716644/20688174/5cff23e4-b585-11e6-93a1-46b5c6e86669.png">

**Comment by mkchandler** [comment]
Thanks @amandaharlin!
