### ISSUE TITLE
Arrange food and drink for OKC FP | 2016-11-29

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/techlahoma#167]
What: OKC Functional Programming
When: 11/29/2016 11:30 AM
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: http://www.meetup.com/OKC-FP/events/235376761/

**Comment by seejessicacode** [comment]
Final headcount: 40
Amount of pizza: Perfect! Just enough leftovers to fill half a pizza box.
Receipt: waiting for a picture...

**Comment by jordan-parmer** [comment]
![okc-fp-food-receipt](https://cloud.githubusercontent.com/assets/5378348/20724913/bd487434-b635-11e6-8160-bd42a5556801.jpg)

**Comment by jordan-parmer** [comment]
![img_20161129_114702](https://cloud.githubusercontent.com/assets/5378348/20724939/da5b4e66-b635-11e6-8f04-c9ecd9acc252.jpg)

**Comment by jordan-parmer** [comment]
![img_20161129_114611](https://cloud.githubusercontent.com/assets/5378348/20724955/ebc666a4-b635-11e6-97a9-4fb9734723d0.jpg)
