### ISSUE TITLE
Arrange food, drink, and venue access for Tulsa Web Devs event | 2017-11-07

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/techlahoma#169]
What: Hack Night
When: 2017-11-07 18:00
Where: 36 East Cameron St., Tulsa

Check meetup for RSVP count: http://www.meetup.com/Tulsa-Web-Devs/events/qjqkbmywpbkb/

**Comment by groovecoder** [comment]
Oops, meetup.com created this for the wrong day. It's supposed to be the **first** Tuesday of every month, which was Nov 1.
