### ISSUE TITLE
Food and Drink Order for OKC JUG - November 8

### ISSUE THREAD

**Issue by jasondlee** [techlahoma/techlahoma#170]
Meeting Date: October 11

Pizza:
- 1 cheese
- 2 pepperoni
- 2 sausage
- 2 supreme
- 1 veggie

Drinks:
- 1 Coke
- 1 Sprite
- 1 Dr. Pepper
- 1 Diet Coke

**Comment by amandaharlin** [comment]
i ordered. it's done.
