### ISSUE TITLE
Arrange food, drink, and venue access for OKGD event | 2016-12-01

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/techlahoma#175]
What: Demo Day
When: 2016-12-01 19:00
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/Oklahoma-Game-Developers/events/235579222/

**Comment by goldfire** [comment]
Looking like around 20 people with Meetup & FB combined. So, probably 5 large (3 pepperoni, 1 sausage, 1 cheese) and 3 sodas?

**Comment by goldfire** [comment]
Since we've had issues the last 2 meetings, just bumping this to make sure our order got placed for tonight. Thanks!

**Comment by amandaharlin** [comment]
hey james! @goldfire <img width="562" alt="screen shot 2016-12-01 at 5 45 07 pm" src="https://cloud.githubusercontent.com/assets/716644/20817551/109bfa70-b7ee-11e6-8b45-d09d95771348.png">

**Comment by amandaharlin** [comment]
oh, just saw that you wanted a sausage pizza. got it ordered ! 
<img width="557" alt="screen shot 2016-12-01 at 5 49 44 pm" src="https://cloud.githubusercontent.com/assets/716644/20817659/9ed12040-b7ee-11e6-9149-310b0025d315.png">
