### ISSUE TITLE
Arrange food, drink, and venue access for Tulsa Web Devs event | 2017-11-20

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/techlahoma#177]
What: Monthly Meeting
When: 2017-11-20 18:00
Where: 36 East Cameron St., Tulsa

Check meetup for RSVP count: https://www.meetup.com/Tulsa-Web-Devs/events/jgkhbmywpbbc/

**Comment by seejessicacode** [comment]
I assume this was handled.
