### ISSUE TITLE
Arrange food and drink for Systems Management in OKlahoma Experts | 2016-12-19

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/techlahoma#179]
What: Systems Management in OKlahoma Experts
When: 12/19/2016 7:00 PM
Where: 1141 W Sheridan, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/Systems-Management-in-OKlahoma-Experts/events/235904907/

**Comment by seejessicacode** [comment]
Test for tonight's meeting. Please discard AFTER 11/29/2016

**Comment by amandaharlin** [comment]
Test group

**Comment by amandaharlin** [comment]
Test group
