### ISSUE TITLE
Arrange food, drink, and venue access for OKC PHP event | 2016-12-08

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/techlahoma#180]
What: Oklahoma City Meetup: Improving Your Development Practices
When: 12/08/2016 6:30 pm
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/OklahomaPHP/events/235984139/

**Comment by michalcarson** [comment]
Hi Amanda,

We have 7 RSVPs for Thursday evening. I think two pizzas would do it--one veggie and one combo.

Do we have key cards yet?

Michal

**Comment by michalcarson** [comment]
@amandaharlin Are we too late to order pizza?

**Comment by amandaharlin** [comment]
oh hey @michalcarson you are not too late. that's was nice of you to ask! 

ada is asleep now and i've got your order queued up. there should be plenty of drinks up at ss46. if there isn't please let me know. 

ava, shes @avasond in techlahoma slack, is the person in charge of keycards. i'll ask her to get yours ready. 👍 

<img width="569" alt="screen shot 2016-12-07 at 10 59 52 pm" src="https://cloud.githubusercontent.com/assets/716644/20998086/e22705d0-bcd0-11e6-9c91-4f9a1cc743b0.png">
