### ISSUE TITLE
Arrange food, drink, and venue access for Tulsa Web Devs event | 2017-12-06

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/techlahoma#182]
What: Hack Night
When: 2017-12-05 18:00
Where: 36 East Cameron St., Tulsa

Check meetup for RSVP count: https://www.meetup.com/Tulsa-Web-Devs/events/qjqkbmywqbhb/

**Comment by groovecoder** [comment]
@jdungan took care of this.
