### ISSUE TITLE
Arrange food, drink, and venue access for OKC JUG event | 01/10/2017 11:30 am

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/techlahoma#196]
What: Topic TBD
When: 01/10/2017 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/okcjug/events/236354888/

**Comment by seejessicacode** [comment]
Moved to https://github.com/techlahoma/user-groups/issues/61

**Comment by seejessicacode** [comment]
Wrong issue.

**Comment by seejessicacode** [comment]
Moved to https://github.com/techlahoma/user-groups/issues/73
