### ISSUE TITLE
Arrange food, drink, and venue access for OKGD event | 2017-01-05

### ISSUE THREAD

**Issue by goldfire** [techlahoma/techlahoma#197]
What: Game Design Workshop
When: 2017-01-05 19:00
Where: 1141 W Sheridan Ave, Oklahoma City

Sorry about the late notice, I forgot to open this issue here (we announced this meetup last week). Looking like around 20 people with Meetup & FB combined. So, probably 5 large pizzas (3 pepperoni, 1 sausage, 1 cheese) and 3 sodas?

**Comment by seejessicacode** [comment]
We have an automation in place to create issues for Meetup groups that only create events as needed (not automated so many months out). So these issues were already created.

Food: https://github.com/techlahoma/user-groups/issues/76
Space: https://github.com/techlahoma/user-groups/issues/77

We're also moving all user group support to github.com/techlahoma/user-groups

Thanks for posting though, better safe than sorry! Some day we'll have a user group leader newsletter to help communicate these processes better @.@

**Comment by goldfire** [comment]
Ah very cool, thanks!
