### ISSUE TITLE
Arrange food, drink, and venue access for OKC Ruby event | 01/12/2017 11:30 am

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/techlahoma#198]
What: DevOps Round Table
When: 01/12/2017 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/OKC-Ruby/events/236678942/

**Comment by jagthedrummer** [comment]
24 people at the meeting

**Comment by jagthedrummer** [comment]
![20170309_112606](https://cloud.githubusercontent.com/assets/58702/23763295/95403436-04be-11e7-9368-6bb441839799.jpg)

**Comment by seejessicacode** [comment]
Whoops! @jagthedrummer I think you meant to post to https://github.com/techlahoma/user-groups/issues/171
