### ISSUE TITLE
Incorrect meetup time for freeCodeCamp OKC

### ISSUE THREAD

**Issue by kacollins** [techlahoma/techlahoma#203]
https://www.techlahoma.org/usergroups/ says that freeCodeCamp OKC is `Every Sunday at 1:00 PM`, and this is not correct. We don't meet every Sunday (Labor Day weekend is an example), and the time varies between 1:00 and 2:00.

**Comment by the-simian** [comment]
What do you propose the verbiage be? 

`Every Sunday, with the exception of national holidays, sometime between 1pm and 2pm`? 
Imagine a new attendee, what do they need to know? What is the most succinct and correct way to express the meeting time

**Comment by kacollins** [comment]
I would prefer something more like `Sunday afternoons`. Members need to use meetup.com to find the correct meeting times, so maybe even add `(check Meetup for time)`.

**Comment by the-simian** [comment]
That makes sense. we can even link to the meetup.

**Comment by kacollins** [comment]
Done!
