### ISSUE TITLE
OKC# website

### ISSUE THREAD

**Issue by Jason9199** [techlahoma/techlahoma#211]
On https://www.techlahoma.org/usergroups please update the OKC# website and listing to point to https://www.meetup.com/OKC-Sharp/ instead of the current http://okcsharp.net/ as this website no longer exists.

**Comment by JeffLowe** [comment]
Done.

**Comment by Jason9199** [comment]
If you click on the group logo it still takes you to http://okcsharp.net/ Can we get that updated too please?

**Comment by JeffLowe** [comment]
Ohh.  Good catch.  Sorry for missing that.  It's resolved now.
