### ISSUE TITLE
Calendar & Events Page

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/techlahoma#29]
How do we update the Events page with events? Do we just use user groups rss feeds or is this something we'd want to implement to let people manually add/edit/delete?

Should we have a community calendar? 

Should the events page have a downloadable link for ical, gmail, etc?

**Comment by amandaharlin** [comment]
A few months ago I added in ug reoccurring dates to a Gmail calendar on techlahoma@gmail.com. I don't think this is robust enough. Wish we had something people could submit events to (that also reminded us to buy pizza ;P)

**Comment by DevinClark** [comment]
Interfacing with the Meetup API could be interesting for this. (Assuming all the groups are on Meetup)

**Comment by amandaharlin** [comment]
+1 on meetup api :sparkles:
