### ISSUE TITLE
Add Drupal User Group

### ISSUE THREAD

**Issue by VeggieMeat** [techlahoma/techlahoma#47]
Oklahoma Drupalers
3rd Thursdays - 7:30pm-9:30pm
Francis Tuttle Rockwell Campus
https://groups.drupal.org/oklahoma-drupalers

**Comment by ryoe** [comment]
@VeggieMeat Thanks for info on Oklahoma Drupalers. Sorry it took so long to get it up on the site. It's live here now: http://us.techlahoma.org/groups

I took a shot at the blurb, so let me know if you want different wording. 

Also, we can add an email address and twitter info if you like.

**Comment by amandaharlin** [comment]
thank you @ryoe! you've gotten so much going lately :) :hamster: great job
on adding in some temp info for @veggiemeat.
