### ISSUE TITLE
Tulsa groups aren't showing up on the live site?

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/techlahoma#51]
https://github.com/techlahoma/techlahoma/pull/44 was merged a while back, but the Tulsa groups aren't showing up at http://us.techlahoma.org/groups ?

**Comment by ryoe** [comment]
Sorry about that Luke. They've been merged into seeds.rb, they're not yet in the live db. I'll get that sorted out.

**Comment by ryoe** [comment]
The Tulsa groups are on the live site now. My apologies for the long delay between merge and live.

**Comment by amandaharlin** [comment]
@ryoe thank you so very much for handling this and getting it live!~

**Comment by the-simian** [comment]
@ryoe thank you! I saw this over the weekend and was swinging back to check on it and you knocked it out long ago!
