### ISSUE TITLE
Signing in is broken

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/techlahoma#52]
I can't sign in via GitHub nor via Twitter. :cry:

**Comment by jagthedrummer** [comment]
@groovecoder I think this should be fixed now. Can you give it another try? (There's still not really anything you can do once you're signed in...)

**Comment by groovecoder** [comment]
Signing in with Twitter worked! w00t!

GitHub got http://us.techlahoma.com/auth/failure?message=redirect_uri_mismatch&strategy=github error page (with a bad style) ...
<img width="670" alt="2016-02-15_0733" src="https://cloud.githubusercontent.com/assets/71928/13050042/7758c346-d3b6-11e5-9cdb-8dee246acd88.png">

**Comment by seejessicacode** [comment]
If this is working, can someone close this issue?
