### ISSUE TITLE
Schedule board meeting

### ISSUE THREAD

**Issue by rhoegg** [techlahoma/techlahoma#53]
We need to schedule our next board meeting.  I would prefer a Sunday, but can probably squeeze in a Monday or Tuesday.

Here's a [Doodle poll](http://doodle.com/7p656cmu779rp8xn) to help choose the day.  I've been using this for a while to schedule OKCJUG steering committee meetings, it's helpful.

Please comment with items you'd like on the agenda.

If this was the wrong project for this issue, please let me know.

**Comment by rhoegg** [comment]
Here are a couple items I want to discuss:
* Budget for Federal 501(c)(3) status
* Sponsorship levels
* How to work with different types of affiliated groups
* Plan our leaders' meeting with Matt@Prototek

**Comment by jagthedrummer** [comment]
+1 on the meeting and all of those topics!

**Comment by amandaharlin** [comment]
I can meet tonight, or really any other night. What about y'all @vlucas @datachomp @DevinClark

**Comment by DevinClark** [comment]
I'm pretty much available whenever.

**Comment by DevinClark** [comment]
Have we decided on anything yet? I probably need to head out soon if today.

**Comment by rhoegg** [comment]
Let's not do today. I'll close the poll tonight.

**Comment by rhoegg** [comment]
It looks like Tuesday the 17th is good for a lot of people.  Let's shoot for that.

**Comment by DevinClark** [comment]
:+1: Sounds good to me.

I think we should also consider creating a 'discussions' project or something for issues like this that don't directly relate to the code in this project.

**Comment by groovecoder** [comment]
We've used 'tasks' repos on GitHub for that kind of thing ...

**Comment by DevinClark** [comment]
Yeah. That's what I'm talking about. I like how CodeForOKC did it. https://github.com/codeforokc/discussions

**Comment by amandaharlin** [comment]
awesome. well, is it ok with everyone to follow CfOKC's use of gitter?

**Comment by groovecoder** [comment]
Honestly, between Email (work, personal, Code for America), GitHub, Bugzilla, IRC (work & freenode), Slack (CfA, Midwest Dev Chat, codesy, tulsa web devs, cultivate918) ... I'm pretty much tapped out on different communication channels.

If we use gitter, let's make sure it somehow propagates to email - the lowest common denominator of communication.

**Comment by DevinClark** [comment]
I'm okay with Gitter. We could also use the techlahoma slack channel maybe?

**Comment by amandaharlin** [comment]
the reason i didn't mention slack was that we needed emails, but since
slack integrates with irc that might actually be a better option. luke's
points on the matter are totally reasonable.

**Comment by DevinClark** [comment]
That makes sense. I assumed Slack had that sort of integration also. So we have decided on Gitter?

**Comment by the-simian** [comment]
I defer to whatever everyone else seems to like the most

**Comment by jagthedrummer** [comment]
So, is the meeting happening today? I think I remember it being 5pm, is that right? Google hang out?

**Comment by rhoegg** [comment]
Yes, I plan to be at the 404 about 5.

**Comment by amandaharlin** [comment]
Same. I think Rob will be out this time. @vlucas can you make it to the 404
or be online at 5 for this?

**Comment by groovecoder** [comment]
I can be online 5pm - 5:30pm.

-L

**Comment by vlucas** [comment]
Yes, I will be at the 404 for this at 5pm.

**Comment by jagthedrummer** [comment]
Dang it, I had something come up and I won't be able to make this. I'd love to read a recap or watch/listen to a recording if at all possible.

**Comment by groovecoder** [comment]
Who has the hangout link?

**Comment by amandaharlin** [comment]
we're keeping minutes in this gist[1] and talking on gitter[2]. thanks for
participating & wanting to help!

[1](https://gist.github.com/the-simian/9f465ebbeb8ec077a667)
[2](https://gitter.im/techlahoma)

**Comment by vlucas** [comment]
Closing this since we had the board meeting last night. :clap:
