### ISSUE TITLE
Please help us promote CodeAcross

### ISSUE THREAD

**Issue by jagthedrummer** [techlahoma/techlahoma#54]
The Code for OKC brigade of Code for America is participating in the annual CodeAcross event. We'd love it if the various Techlahoma user groups could help us promote this event. 

There are two parts to the event.

Friday Feb 20 : 10am-11am at OKC City Hall - We're trying to host a meeting at city hall to be able to have Code for OKC members meet with city gov't officials to discuss ways that we can work together. This meeting is currently tentative, and we're working out the details.

Saturday Feb 21 : 10am - 4pm - CodeAcross hackathon at Prototek. We plan to have a few presentations on the US Open Data Census, Visualizing Open Data with D3.js, and Mapping Open Data with Leaflet.js and Mapbox. We'll also have some open hack time to work on our school-finder project, and to discuss/kickstart new projects.

The Meetup event for the hackathon is here:
http://www.meetup.com/Code-for-OKC/events/220289855/

You can see more about CodeAcross in general here:
http://www.codeforamerica.org/events/codeacross-2015/

And the Code for Okc website is:
http://codeforokc.org/

Thanks!

**Comment by the-simian** [comment]
Thanks for posting this!
