### ISSUE TITLE
Add Code for OKC to group listings

### ISSUE THREAD

**Issue by mkchandler** [techlahoma/techlahoma#55]
Description: Code for OKC is a Code for America Brigade helping innovate government and make OKC better using the open web.
When: 4th Monday at 6:00 PM
Where: Prototek
Contact: [website](http://codeforokc.org) / [twitter](https://twitter.com/codeforokc)

The image can be pulled off our github profile if needed: https://github.com/codeforokc

**Comment by the-simian** [comment]
YES!

**Comment by amandaharlin** [comment]
thank you so much!!

**Comment by datachomp** [comment]
@seejessicacode has knocked this one out.
