### ISSUE TITLE
Need to add OKCSharp to http://us.techlahoma.org/groups

### ISSUE THREAD

**Issue by matthewreily** [techlahoma/techlahoma#58]
Not sure if this is the right place to open an issue or not.  The OKC-Sharp information is missing from list of groups on the http://us.techlahoma.org/groups page.  I'd be happy to add it if someone would be willing to walk me through it :)

**Comment by the-simian** [comment]
Yep! thanks man! This is indeed the place to open this

**Comment by the-simian** [comment]
I'll swing by and handle entry.

**Comment by seejessicacode** [comment]
^bump
I don't see OKC# on http://us.techlahoma.org/groups or http://techlahoma.org/groups.html

**Comment by seejessicacode** [comment]
https://github.com/techlahoma/techlahoma_lander/issues/25

**Comment by jagthedrummer** [comment]
The user groups list now lives in the `techlahoma_lander` project. 

https://github.com/techlahoma/techlahoma_lander/tree/master/data

**Comment by seejessicacode** [comment]
Can somebody close this issue please?
