### ISSUE TITLE
Order pizza for OKC-Sharp on Monday November 2nd

### ISSUE THREAD

**Issue by matthewreily** [techlahoma/techlahoma#61]
Can someone order pizza for OKC-Sharp's meeting on Monday November 2nd?  We have 24 registered as of Thursday evening and might have a few more.

**Comment by the-simian** [comment]
![image](https://cloud.githubusercontent.com/assets/954596/10874530/d24426c4-80eb-11e5-8628-b8cd2dc5fcda.png)

**Comment by the-simian** [comment]
This is set to arrive at 11:15AM tomorrow at Prototek
