### ISSUE TITLE
Need to place OKC-Sharp pizza order for 12-7-2015 and open the door at Prototek

### ISSUE THREAD

**Issue by matthewreily** [techlahoma/techlahoma#65]
Our OKC-Sharp meeting is tomorrow and we currently anticipate 28 attendees.  Can we get pizza ordered and also have someone with a badge let us in Prototek?

Thanks!

**Comment by amandaharlin** [comment]
:+1: @the-simian will come let y'all in. pizza is ordered too. :-)

<img width="931" alt="screen shot 2015-12-06 at 8 46 23 pm" src="https://cloud.githubusercontent.com/assets/716644/11617944/9b308148-9c5a-11e5-9fcc-688495480389.png">
