### ISSUE TITLE
Buy Pizza OKC-Sharp 01-04-2016

### ISSUE THREAD

**Issue by matthewreily** [techlahoma/techlahoma#69]
Can someone please buy pizza for the meeting?  We have 10 signed up so far and might get a few more between now and then.

**Comment by amandaharlin** [comment]
ordered :+1: <img width="1116" alt="screen shot 2016-01-04 at 10 13 32 am" src="https://cloud.githubusercontent.com/assets/716644/12094025/dbf0bcf2-b2cb-11e5-956b-8f2600a80558.png">
