### ISSUE TITLE
Let OKC-Sharp in at Prototek 01-04-2016 @11:15

### ISSUE THREAD

**Issue by matthewreily** [techlahoma/techlahoma#70]
Can someone with a badge pretty please let us in?

**Comment by amandaharlin** [comment]
can you call jesse? @the-simian 

if he can't, maybe ryan @rhoegg might have a card at the 404.

**Comment by rhoegg** [comment]
I'll be there

**Comment by amandaharlin** [comment]
YES!!! thank you ryan. you've been ridiculously accommodating this week
(like usual) :sparkles:
