### ISSUE TITLE
move the techlahoma site code to another repo?

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/techlahoma#73]
just wondering if we should split up discussion/todos and website code into 2 different repos (like 200okc-site for website and 200ok for getting non-site stuff done)

**Comment by jagthedrummer** [comment]
@amandaharlin Is the `techlahoma/discussions` repo not good for the discussion half of things? (Maybe I'm misunderstanding the goal of this issue?)

**Comment by seejessicacode** [comment]
There does seem to be a lot of places for people to report bugs/concerns or ask questions. Maybe we could encourage non-contributing members to post to techlahoma/discussions and have a few board volunteers moderate it and echo the concerns to concerning project repo if necessary?
