### ISSUE TITLE
social media help - help wanted

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/techlahoma#74]
would anyone like to help with social media? (buffer, twitter, facebook) i've been doing it but sometimes need a backup for announcing weekly activities or other things.

**Comment by seejessicacode** [comment]
@amandaharlin Let's get together and compile a list of what we've got cookin' social media wise before the Town Hall meeting. I find it's easier to get help when you have a list for volunteers to choose from.

**Comment by RicksConcepts** [comment]
I'd being interested in help as well.

**Comment by amandaharlin** [comment]
having some help would be great! :+1: maybe we can all get together
sometime in norman/online and queue up some stuff?

**Comment by RicksConcepts** [comment]
Just let me know. I'll work it out to be tehre.

**Comment by the-simian** [comment]
also what @seejessicacode and I have planned might help. possibly could automate more with buffer
