### ISSUE TITLE
order pizza, pop for codeforokc

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/techlahoma#75]
<img width="780" alt="screen shot 2016-01-25 at 4 46 11 pm" src="https://cloud.githubusercontent.com/assets/716644/12567177/35e4e1d0-c383-11e5-9611-6983e7a43181.png">

@mkchandler @jagthedrummer :+1:

**Comment by mkchandler** [comment]
Thanks @amandaharlin!
