### ISSUE TITLE
Order pizza for Code for OKC February meeting

### ISSUE THREAD

**Issue by mkchandler** [techlahoma/techlahoma#79]
Need to order pizza for our February hack night tonight.

### Details

Attendees: 10 (based on Meetup RSVP + previous history of people who show up)
Number of pizzas: 3 large (2 pepperoni, 1 cheese)
Soda: 2 (1 sprite, 1 coke, or random :smile:)
Delivery time: 6:00 PM
Location: Prototek

Let me know if you need anymore info!

cc: @amandaharlin

**Comment by amandaharlin** [comment]
perfect! 👏 thanks so much for this format.

ordered 2 pep, 1 cheese, 1 sprite, 1 coke to be delivered on 2/22 at 6pm to
prototek.

**Comment by mkchandler** [comment]
thanks @amandaharlin :pizza: :pizza:

**Comment by mkchandler** [comment]
Pizza and drinks have arrived. Thanks again!
