### ISSUE TITLE
Pizza/drinks for March Code for OKC meeting

### ISSUE THREAD

**Issue by mkchandler** [techlahoma/techlahoma#82]
Attendees: 10 (based on Meetup RSVP + previous history of people who show up)
Number of pizzas: 3 large (2 pepperoni, 1 cheese)
Soda: 2 (1 sprite, 1 coke, or random :smile:)
Delivery time: 6:00 PM
Location: Prototek

cc: @amandaharlin

**Comment by amandaharlin** [comment]
thanks Matt!

**Comment by amandaharlin** [comment]
and ordered :+1: large 2 pep, 1 cheese, 2 liter of sprite and coke, will be delivered to prototek at 6pm tonight
