### ISSUE TITLE
Projection screen is coming off the roll

### ISSUE THREAD

**Issue by mmattice** [techlahoma/techlahoma#86]
I had a meeting after okcpy today, otherwise I would have spent more time on it, but the screen is not in a state in which it can be rolled up without damaging it.  So I didn't roll it up.

Pinged @amandaharlin on slack for possible people coordination to get it fixed, since I have no idea who would have that knowledge/ability.

**Comment by the-simian** [comment]
yeah i heard about this. huge bummer. may just need to get a new one, its been getting worse and worse

**Comment by amandaharlin** [comment]
board meeting is on tuesday. we could vote to get one then. i'm certain
it'll pass.

**Comment by seejessicacode** [comment]
I didn't find anything in the board meeting minutes regarding the projector. Is the plan to still order a new projector screen?

**Comment by amandaharlin** [comment]
the groups have started using the nice tv's prototek installed. since we'll likely be moving within the next couple of months i think the plan is to purchase the projector and install it at the community hub.
