### ISSUE TITLE
RefreshOKC pizza

### ISSUE THREAD

**Issue by RicksConcepts** [techlahoma/techlahoma#88]
Requesting pizza for approx 30 people for the refreshOKC meeting on 2016-04-26

cc @amandaharlin

**Comment by RicksConcepts** [comment]
I just saw the weather so I'm going to be monitoring the weather until Tuesday. Hopefully it clears up by then.

**Comment by the-simian** [comment]
Thanks @RicksConcepts , yeah lets keep an eye on that

**Comment by RicksConcepts** [comment]
@the-simian @amandaharlin I went ahead and cancelled the meetup tonight. Figured I'd rather be safe than sorry.

**Comment by amandaharlin** [comment]
That was the right call. Thanks Rick! Stay safe!

**Comment by seejessicacode** [comment]
Can one of you cool peeps close this issue?
