### ISSUE TITLE
OKC-Sharp Pizza for May Meeting

### ISSUE THREAD

**Issue by matthewreily** [techlahoma/techlahoma#91]
We need to get pizza ordered for Monday May 2nd OKC-Sharp meeting.  We currently have 30 members registered to attend.

Thanks!

**Comment by davidroberts63** [comment]
Do we have anyone lined up to bring drinks? If not I can bring some. Just let me know.

**Comment by matthewreily** [comment]
We usually order some when we get the pizza.  More the merrier though!

**Comment by seejessicacode** [comment]
May 2 has come and gone. It's time to close this baby!
