### ISSUE TITLE
Pizza/Drinks for May OKGD Meeting

### ISSUE THREAD

**Issue by goldfire** [techlahoma/techlahoma#93]
Pizza/drinks order for May 5th Oklahoma Game Developers meeting:

**Attendees:** ~30
**Number of pizzas:** 6 large (3 pepperoni, 2 sausage, 1 cheese)
**Soda:** 3 (1 sprite, 1 coke, 1 coke zero)
**Delivery time:** Thursday, May 5th at 7:00 PM
**Location:** Prototek

cc: @amandaharlin

**Comment by amandaharlin** [comment]
Hey @goldfire, the order is for tonight, right? Just double checking

**Comment by goldfire** [comment]
Yes, sorry about that, May 5th, not May 7th. I even double-checked my post and somehow still didn't catch that.

**Comment by amandaharlin** [comment]
Thanks so much! I've ordered pizza on the wrong day before >.< double
checking helps lol

**Comment by amandaharlin** [comment]
Order placed 👍
Large 3 pep, 2 sausage, 1 cheese
1 coke, 1 sprite, and 2 coke zero's in 20 Oz bottles (they were out of 2 liters). Should be delivered to Prototek at 7pm tonight. 
Thanks James!
