### ISSUE TITLE
okcruby food for May Meeting

### ISSUE THREAD

**Issue by datachomp** [techlahoma/techlahoma#95]
group: okcruby
food type:  pizza
guest approximation: 15
meeting date: May 12th, 2016 11:30

For visibility, 
organizers: @jagthedrummer @piisalie @datachomp

**Comment by jagthedrummer** [comment]
Would be nice to do something non-pizza for a change. We do have some vegetarian members, so we need some veggie options.

**Comment by amandaharlin** [comment]
Whatever y'all want, just let me know. Don't have time rn for researching good alternatives that include veg options, but I can place the order (or jesse, ryan or vance can) :(

**Comment by jagthedrummer** [comment]
Yeah, sorry, didn't mean to put that on you. I don't really have any other options at the ready. I guess we better just go with pizza since it's well understood. Thanks, @amandaharlin! 😄

**Comment by datachomp** [comment]
Just checking in real quick... did this get ordered so we can close out the issue?

**Comment by amandaharlin** [comment]
<img width="659" alt="screen shot 2016-05-12 at 10 09 35 am" src="https://cloud.githubusercontent.com/assets/716644/15219506/a940fc54-1829-11e6-91b3-1982bf8da7a2.png">
just ordered jimmy johns with 2 veggie sandwiches (which are cut in half). didn't know how many vegetarians there were =/ can one of you pick up some 2 liters of soda on your way there? there's a gas station nearby on sheridan, right off the highway.

**Comment by jagthedrummer** [comment]
Thanks, @amandaharlin! I'll grab some sodas on the way.

**Comment by amandaharlin** [comment]
perfect! at the new space we'll stock up on soda, water, cups, plates, and napkins so this will just be a thing of the past! 😎 :cool:

**Comment by datachomp** [comment]
❤️
