### ISSUE TITLE
OKC SQL meetup address is incorrect

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/techlahoma#96]
As reported in an email to Techlahoma from Kimberly Collins.

"Is the Techlahoma Google calendar kept up to date?  I was looking up the address for the OKC SQL meetup and found that it still shows the group as meeting at Dell.  I looked into it more and found that it's wrong here too:  http://us.techlahoma.org/groups

I'm also not sure whether anyone monitors the email address listed on that page (info@okcsql.org)."

Please update the following:
- [x] Google calendar
- [x] Techlahoma user group page

**Comment by jagthedrummer** [comment]
The user groups list now lives in the `techlahoma_lander` project. 

https://github.com/techlahoma/techlahoma_lander/tree/master/data

**Comment by seejessicacode** [comment]
I removed the address from the recurring event on Techlahoma's google calendar and added http://www.okcsql.org/ to the event description.
