### ISSUE TITLE
Add OKCMySQL to Techlahoma's user group website and announcements.

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/techlahoma#97]
I've confirmed with @amandaharlin that @mbenshoof and the rest of the OKCMySQL crew are joining the Techlahoma family!

We just need to implement the following to make it official:

- [ ] Move OKCMySql from the "Other Groups" section to the "User Groups" section

- [ ] Include OKCMySql's meetup announcements in the techlahomie twitter bot's Twitter

**Comment by jagthedrummer** [comment]
The user groups list now lives in the `techlahoma_lander` project. 

https://github.com/techlahoma/techlahoma_lander/tree/master/data

**Comment by seejessicacode** [comment]
{
"name": "OKC MySQL",
"website": "http://www.meetup.com/Oklahoma-City-MySQL-Meetup/",
"logo_url": "",
"twitter": "okcmysql",
"location": "the 404",
"meetupdate": "4th Wednesday",
"email": "info@okcmysql.org",
"blurb": "OKC MySQL is a group of MySQL users that meet to discuss various topics related to the MySQL ecosystem."
}

Their official website (http://okcmysql.org/) hasn't been updated since last year, so I used their meetup url instead.

I also copied and refactored the blurb from their meetup group description.

**Comment by seejessicacode** [comment]
Image from twitter account
![image](https://cloud.githubusercontent.com/assets/943398/15560735/0763ace8-22b4-11e6-9258-558aed27b867.png)

**Comment by jagthedrummer** [comment]
I'm seeing the MySql group on this page : http://www.techlahoma.org/usergroups

I think we can close this issue

**Comment by seejessicacode** [comment]
Agreed.
