### ISSUE TITLE
Food/drinks for May Code for OKC meeting

### ISSUE THREAD

**Issue by mkchandler** [techlahoma/techlahoma#98]
Pizza/drinks order for tonight's Code for OKC meeting:

Attendees: 8-10 (based on Meetup RSVP + previous history of people who show up)
Number of pizzas: 2 large (1 pepperoni, 1 cheese)
Soda: 1 (1 coke)
Delivery time: Monday, May 23rd at 6:00 PM
Location: Prototek

cc: @amandaharlin

**Comment by amandaharlin** [comment]
ordered! :) have a good meeting 👍 <img width="917" alt="screen shot 2016-05-23 at 1 26 11 pm" src="https://cloud.githubusercontent.com/assets/716644/15480208/f39b2c70-20e9-11e6-9225-0d53ec2b906d.png">

**Comment by mkchandler** [comment]
Thanks @amandaharlin!!!
